// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1JfnQ8bZmo3_hCyIiqgjoAJC2RQhpK6U',
    appId: '1:415349357217:web:4f66df472bf446d1848ee0',
    messagingSenderId: '415349357217',
    projectId: 'foodorder-e9a29',
    authDomain: 'foodorder-e9a29.firebaseapp.com',
    storageBucket: 'foodorder-e9a29.appspot.com',
    measurementId: 'G-VJ8LHBY14P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu_d6suE9ryJVu8vJiEFxyqOCNYxANHq8',
    appId: '1:415349357217:android:ce8d75fca75844b2848ee0',
    messagingSenderId: '415349357217',
    projectId: 'foodorder-e9a29',
    storageBucket: 'foodorder-e9a29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_eKnE4QLWfW7jwc2WrttUGVUvMpuOCLs',
    appId: '1:415349357217:ios:812214edd785f1ee848ee0',
    messagingSenderId: '415349357217',
    projectId: 'foodorder-e9a29',
    storageBucket: 'foodorder-e9a29.appspot.com',
    iosBundleId: 'com.example.foodOrderKelompok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_eKnE4QLWfW7jwc2WrttUGVUvMpuOCLs',
    appId: '1:415349357217:ios:812214edd785f1ee848ee0',
    messagingSenderId: '415349357217',
    projectId: 'foodorder-e9a29',
    storageBucket: 'foodorder-e9a29.appspot.com',
    iosBundleId: 'com.example.foodOrderKelompok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1JfnQ8bZmo3_hCyIiqgjoAJC2RQhpK6U',
    appId: '1:415349357217:web:96857680fcd3ca04848ee0',
    messagingSenderId: '415349357217',
    projectId: 'foodorder-e9a29',
    authDomain: 'foodorder-e9a29.firebaseapp.com',
    storageBucket: 'foodorder-e9a29.appspot.com',
    measurementId: 'G-G7MLF7N8N5',
  );

}